name: Build and Push Flask App

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: flask-todo

jobs:
  build-and-push:
    runs-on: sam-desktop
    permissions:
      contents: write  # Need write permission to update the manifest
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract tag version
        id: tag
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Flask app image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.version }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

      - name: Update deployment manifest
        run: |
          git config --global user.email "info@tekanaid.com"
          git config --global user.name "TeKanAid Automation"
          
          # Update the image tag in the deployment manifest
          sed -i 's#ghcr.io/${{ github.repository_owner }}/flask-todo:.*#ghcr.io/${{ github.repository_owner }}/flask-todo:${{ steps.tag.outputs.version }}#g' flask-deployment.yaml
          
          # Commit and push the changes
          git add flask-deployment.yaml
          git commit -m "Update Flask deployment to use image tag ${{ steps.tag.outputs.version }}"
          git push