name: Build and Push Flask App

on:
  push:
    tags:
      - 'v*'  # Only trigger on version tags

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: flask-todo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        id: tag
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.version }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

      - name: Update deployment manifest
        run: |
          git config --global user.email "info@tekanaid.com"
          git config --global user.name "TeKanAid Automation"
          
          # Fetch all branches
          git fetch origin
          
          # Checkout main branch
          git checkout main
          
          # Update the manifest
          sed -i "s|image: ghcr.io/samgabrail/flask-todo:.*|image: ghcr.io/samgabrail/flask-todo:${{ steps.tag.outputs.version }}|" flask-deployment.yaml
          
          # Stage, commit and push
          git add flask-deployment.yaml
          git commit -m "Update deployment to version ${{ steps.tag.outputs.version }}"
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main
