# Default values for spot-config-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  labels: {}
  # Remove the {} and add any needed values to your SecurityContext
  securityContext: {}
#    fsGroup: 3000
#    runAsUser: 65534

replicaCount: 2
openshiftEnabled: false
debug: false

gatewayCert:
  #  Specifies an existing secret for gateway tls certificate must include:
  # - tls.crt (base64)
  tlsCertsSecretName:

#Remove the {} and add any needed values to your SecurityContext here, do not change runAsUser and allowPrivilegeEscalation
containerSecurityContext: {}
#  seccompProfile:
#    type: RuntimeDefault

image:
  repository: docker.registry-2.akeyless.io/k8s-webhook-server
  agentImage: docker.registry-2.akeyless.io/k8s-secrets-sidecar

##   Alternative mirror registry
#  repository: akeyless/k8s-webhook-server
#  agentImage: akeyless/k8s-secrets-sidecar

  pullPolicy: IfNotPresent

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  # name: ""
  # Optional additional annotations to add to the controller's ServiceAccount
  # annotations: {}
  # Automount API credentials for a Service Account.
  automountServiceAccountToken: true
  labels: {}

restartRollout:
  enabled: false
  interval: 1m

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 30
  failureThreshold: 5

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 5

service:
  name: secrets-webhook
  type: ClusterIP
  externalPort: 443
  internalPort: 8443
  labels: {}

# for EKS using custom CNI
#hostNetwork: true

env:
  AKEYLESS_URL: "https://vault.akeyless.io"
  AKEYLESS_ACCESS_ID: "p-trkddl1zvs2qkm" 
  AKEYLESS_ACCESS_TYPE: "k8s"  # azure_ad/aws_iam/api_key/k8s

  AKEYLESS_API_GW_URL: "https://192.168.1.82:8080"
 # AKEYLESS_POD_ACCESS_PATH: "<location-to-access-secrets-per-pod-name>"
 # AKEYLESS_NAMESPACE_ACCESS_PATH: "<location-to-access-secrets-per-namespace>"
 # AKEYLESS_SECRET_DIR_NAME: "<path>"
 # AKEYLESS_API_KEY: "<api_key>"
 # AKEYLESS_CRASH_POD_ON_ERROR: "enable"
  AKEYLESS_K8S_AUTH_CONF_NAME: "/demos/K8s-Auth-for-Demos"
 
 # the gw base64 certificate file e.g: 'cat my-gw.crt | base64'
  AKEYLESS_GW_CERTIFICATE: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtRENDQW9DZ0F3SUJBZ0lVRmkrQXA2T0c5c3ZSQ0w2UjZaakJMN1ZhV2xRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1hERUxNQWtHQTFVRUJoTUNRMEV4RURBT0JnTlZCQWdNQjA5dWRHRnlhVzh4RVRBUEJnTlZCQWNNQ0U5aAphM1pwYkd4bE1SRXdEd1lEVlFRS0RBaFVaVXRoYmtGcFpERVZNQk1HQTFVRUF3d01kR1ZyWVc1aGFXUXVZMjl0Ck1CNFhEVEkwTURjeU5ESXpNRFUxTVZvWERUSTNNRFF5TURJek1EVTFNVm93WERFTE1Ba0dBMVVFQmhNQ1EwRXgKRURBT0JnTlZCQWdNQjA5dWRHRnlhVzh4RVRBUEJnTlZCQWNNQ0U5aGEzWnBiR3hsTVJFd0R3WURWUVFLREFoVQpaVXRoYmtGcFpERVZNQk1HQTFVRUF3d01kR1ZyWVc1aGFXUXVZMjl0TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBckpiUXZOcU9HcFAza1BSVU1PZE41aytYRlJ6YkNuMXI0c3RlM2wxS0FaUkEKZUN5RTYxVjFSdzM5Tk9vK0Z4bGEvQ0hJN3dXeVFTZWtXa1lQVUJTMjNBSWFROUs5eDBuNWg4SlYyYWRXekY4Two3OTVjRlhhUzNlb3J3ZktHQVFqY2s4aHNEWWdvSHdSdE9kZTdKMVR6dldsS2JpbGpZVUhnRWRoQ1V6Rzhhd2hjCnFHemxYQWQzTVFKQ0loZDVxaWdzNU9uNjRwZGZNR0QrQ09nTXdZQktickVrRGdwRE1nTjJTVU8zOFUvUFl5MUIKT292SitMNFVldHd3NlZtVXQ2TmpuNDVlSkd2WCtWaDlwek94SmJCYnpaNEZsa3k3Zys2eHNwNEdTcGMveVhuMAo2NWlxNzdrazNQblh0VmJ0dk5qWlBYN05lYVVRVFluVVVJaFp0Q0NkNlFJREFRQUJvMUl3VURBdkJnTlZIUkVFCktEQW1nZ3gwWld0aGJtRnBaQzVqYjIySEJNQ29BVktIQk1Db0FWT0hCTUNvQVZTSEJIOEFBQUV3SFFZRFZSME8KQkJZRUZEemVpZ05ncHFUUnpRVlZGSG90ODNReXRjOW9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNkTXlaUwo3SWYzN0dQY1Zyd0wxaWVzYWNBTWpiQS9DMGdkL2NnTEpMNlZzdXJEeTF1YUNJUFEyNTZKM25SbWNkNmRiNkFmCmtxejZ4bUtRYmtpazhOLzg4ZG1vTXdSQUMwZmNiaXEwWWd5djN3TGM0MnBMRXVrYm5LckF1cC9DZGpTa3NlN3IKeCtrMHB0RWZTU3A2Y2lza3BURHNQMCtYZzdyMFZvVUpWcEppYnppYmEyRXlxYVpNVDhVdXZEeUc0TnpSRXNpQQowTmN2SnNoc2NRazRoVXBhZlhybXZTOWl6dE1wRkYzbE10cFgxay92UWZYWVVWUmVvdklwUkZzZGg4bTdXMUFFCkZvSWVtUEFVZDg2d2FKc0FTNUVNcEdSOWlDTlhSMThvRDRDT0I3M0dlc211a3ZjbUFFYVg0dUJzY1pIM0x1TWwKTHR2VVpQQ3gxNVV1Y3Z3QQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t


  AKEYLESS_AGENT_LIMITS_CPU: "500m"
  AKEYLESS_AGENT_REQUESTS_CPU: "250m"
  AKEYLESS_AGENT_LIMITS_MEM: "128Mi"
  AKEYLESS_AGENT_REQUESTS_MEM: "64Mi"
 

resources:
  limits:
    cpu: 0.5
    memory: 192Mi
  requests:
    cpu: 0.25
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: |
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        topologyKey: kubernetes.io/hostname
        labelSelector:
          matchLabels:
            app: {{ template "vault-secrets-webhook.name" . }}
            release: {{ .Release.Name }}

HPA:
  # Note that metrics server must be installed for this to work:
  # https://github.com/kubernetes-sigs/metrics-server
  enabled: false
  minReplicas: 1
  maxReplicas: 14
  cpuAvgUtil: 50
  memAvgUtil: 50

  annotations: {}