apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{APP_NAME}}
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{APP_NAME}}
  template:
    metadata:
      labels:
        app: {{APP_NAME}}
      annotations:
        akeyless/enabled: "true"
        akeyless/inject_file: "{{AKEYLESS_MYSQL_SECRET_NAME}}_dynamic|location=/akeyless/secrets/db-creds.json"
        akeyless/side_car_enabled: "true"
        akeyless/side_car_refresh_interval: "5s"
        akeyless/side_car_versions_to_retrieve: "1"
    spec:
      volumes:
        - name: secrets-volume
          emptyDir: {}
      containers:
        - name: flask-app
          image: your-docker-registry/flask-app:latest
          volumeMounts:
            - name: secrets-volume
              mountPath: /akeyless/secrets
              readOnly: true
          env:
            - name: DB_HOST
              value: mysql-{{APP_NAME}}
            - name: DB_NAME
              value: {{DB_NAME}}
            - name: FLASK_APP
              value: run.py
          ports:
            - containerPort: 8080

