apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{APP_NAME}}
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{APP_NAME}}
  template:
    metadata:
      labels:
        app: {{APP_NAME}}
    spec:
      containers:
        - name: flask-app
          image: your-docker-registry/flask-app:latest
          env:
            - name: DB_HOST
              value: mysql-{{APP_NAME}}
            - name: DB_NAME
              value: {{DB_NAME}}
            - name: DYNAMIC_SECRET_TTL
              value: "{{DYNAMIC_SECRET_TTL}}"
            - name: FLASK_APP
              value: run.py
            - name: ENVIRONMENT
              value: remote
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: gateway-cert-volume
              mountPath: /etc/ssl/certs/gateway_cert.pem
              subPath: gateway_cert.pem
      volumes:
        - name: gateway-cert-volume
          secret:
            secretName: gateway-cert-secret
